### PR TITLE
Added vertical text to multi-day events

### PR DESCRIPTION
**Pull request by martinlong1978**
This is very rough around the edges, and the bars need to be scaled to about 1.5 in the settings for it to look nice. However, I really like it, and you might like the idea. You'd probably want to review it to make it work with all the settings etc. Also it can overlap with single-day events which is annoying, but I'm not good enough with html/css to get it right.

### CODE REVIEW

**Comment by richardstrong** [comment]
Hi @ctcode, discovered Visual Planner today – just what I was looking for! But for me too it's missing this one essential feature. What would need to happen for you to accept the request? I'd be happy to make any amendments you want.

**Comment by ctcode** [comment]
The visual-planner app is currently undergoing a major rewrite/redesign so probably not worth spending time on updates to the old version. Will have a look at this again after the new version is published.

**Comment by richardstrong** [comment]
OK, look forward to it. Really useful tool! Thanks!

**Comment by martinlong1978** [comment]
I've tidied this up and created a new pull request. 

@richardstrong You could have a look at my hosted version: https://martinlong1978.github.io/visual-planner/vp.htm

**Comment by richardstrong** [comment]
@martinlong1978 nice, works for me. Thanks!

Couple of ideas:
* I have quite a few events of exactly 1 day and these are being displayed as vertical bars. Label is, of course, unreadable. For me it would make more sense to keep these as a horizontal entry and only go vertical when the event spans *multiple* days.
* Where the bar is short and the text long, going to 2 lines (or maybe more) would be good. But that is perhaps trickier to implement.
* When a label is truncated, a couple more characters would be more useful to me than the ellipsis. If you want to visually signal the truncation another possibility which doesn't cost any chars would be to fade the end of the label a little.

**Comment by martinlong1978** [comment]
@richardstrong 

> @martinlong1978 nice, works for me. Thanks!

Excellent

> * I have quite a few events of exactly 1 day and these are being displayed as vertical bars. Label is, of course, unreadable. For me it would make more sense to keep these as a horizontal entry and 
only go vertical when the event spans _multiple_ days.

Go into settings and unselect "Single day as multi-day (vertical bar)."

> * Where the bar is short and the text long, going to 2 lines (or maybe more) would be good. But that is perhaps trickier to implement.

yeah, might be a bit of a faff. May have a look if i get time.

> * When a label is truncated, a couple more characters would be more useful to me than the ellipsis. If you want to visually signal the truncation another possibility which doesn't cost any chars would be to fade the end of the label a little.

maybe something for @ctcode to have a look at. :)

**Comment by richardstrong** [comment]
Ah sorry, should have caught that setting. And duh – the truncation is of course not your work either. Seems I need a coffee  :)   Thanks

**Pull request closed without merging**
